# fly.toml app configuration file generated for vamos-web-shinjan on 2026-04-23T22:21:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vamos-web-shinjan'
primary_region = 'bom'

[build]
  dockerfile = 'apps/web/Dockerfile'

  [build.args]
    NEXT_PUBLIC_API_URL = 'https://vamos-api-shinjan.fly.dev'

[env]
  API_URL = 'https://vamos-api-shinjan.fly.dev'
  NEXT_PUBLIC_API_URL = 'https://vamos-api-shinjan.fly.dev'
  NODE_ENV = 'production'
  PORT = '4247'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
