// Turn a thread into a well-formatted markdown document.

import type { SerializedMsg, Thread } from "@/lib/threads";

export function threadToMarkdown(thread: Thread, portfolioName: string): string {
  const lines: string[] = [];
  lines.push(`# ${thread.title}`);
  lines.push("");
  lines.push(
    `*${portfolioName} · ${new Date(thread.updatedAt).toLocaleString()}*`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const m of thread.messages) {
    lines.push(renderMsg(m));
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by Vamos · ${thread.messages.length} messages · thread ${thread.id}_`,
  );
  return lines.join("\n");
}

function renderMsg(m: SerializedMsg): string {
  if (m.role === "user") {
    return `**You:** ${m.text}`;
  }
  switch (m.kind) {
    case "text":
      return `**Aarthik:** ${m.text}`;
    case "market": {
      const t = m.trend;
      const gainers = t.top_gaining_sectors
        .map(([s, p]) => `${s} ${fmtPct(p)}`)
        .join(", ");
      const losers = t.top_losing_sectors
        .map(([s, p]) => `${s} ${fmtPct(p)}`)
        .join(", ");
      return [
        `### Market snapshot · ${t.overall_sentiment}`,
        `${t.rationale}`,
        ``,
        `**Top gainers:** ${gainers}`,
        `**Top losers:** ${losers}`,
      ].join("\n");
    }
    case "news": {
      const rows = m.news
        .map(
          (n) =>
            `- **${n.article.source}** — ${n.article.headline} *(${n.article.sentiment.toLowerCase()}, impact ${n.relevance_score.toFixed(2)})*`,
        )
        .join("\n");
      return `### Classified news · ${m.news.length} signals\n${rows}`;
    }
    case "risk": {
      const a = m.analytics;
      const sectors = Object.entries(a.sector_allocation)
        .sort(([, x], [, y]) => y - x)
        .map(([n, w]) => `- ${n}: ${w.toFixed(1)}%`)
        .join("\n");
      const alerts = a.alerts
        .map((al) => `- **[${al.level}]** ${al.message}`)
        .join("\n");
      return [
        `### Risk analysis`,
        `Concentration risk: **${a.concentration_risk ? "YES" : "no"}**`,
        ``,
        `**Sector allocation:**`,
        sectors,
        alerts ? `\n**Alerts:**\n${alerts}` : "",
      ].join("\n");
    }
    case "reasoning": {
      const steps = m.steps
        .map(
          (s) =>
            `- [${s.status === "done" ? "✓" : s.status === "active" ? "…" : " "}] **${s.label}** — ${s.detail}${s.duration_ms ? ` *(${(s.duration_ms / 1000).toFixed(1)}s)*` : ""}`,
        )
        .join("\n");
      const tokens = m.tokenUsage
        ? ` · ${m.tokenUsage.input_tokens ?? 0} in / ${m.tokenUsage.output_tokens ?? 0} out tokens`
        : "";
      const total = m.totalMs
        ? ` · ${(m.totalMs / 1000).toFixed(1)}s`
        : "";
      return `### Reasoning trace${total}${tokens}\n${steps}`;
    }
    case "briefing": {
      const b = m.briefing;
      const chains = b.causal_chains
        .map(
          (c) =>
            `  - ${c.trigger} → **${c.sector}** (${fmtPct(c.sector_impact_pct)}) → ${c.stocks.join(", ") || "—"} → portfolio ${fmtPct(c.portfolio_impact_pct)}\n    ${c.narrative}`,
        )
        .join("\n");
      const insights = b.key_insights
        .map((i) => `- **[${i.severity}] ${i.title}** — ${i.detail}`)
        .join("\n");
      const conflicts = b.conflicts
        .map(
          (c) =>
            `- **${c.stock_or_sector}**: news says *${c.news_signal}*, price says *${c.price_signal}* — ${c.explanation}`,
        )
        .join("\n");
      const recs = b.recommendations.map((r) => `- ${r}`).join("\n");
      const evalLine = m.evaluation
        ? `**Self-evaluation:** ${(m.evaluation.score * 100).toFixed(0)}% · depth ${m.evaluation.causal_depth} · ${m.evaluation.method}`
        : "";
      return [
        `### Briefing · confidence ${(b.confidence * 100).toFixed(0)}%`,
        ``,
        `> ${b.headline}`,
        ``,
        b.summary,
        ``,
        chains ? `**Causal chains:**\n${chains}` : "",
        insights ? `\n**Key insights:**\n${insights}` : "",
        conflicts ? `\n**Conflicting signals:**\n${conflicts}` : "",
        recs ? `\n**Recommendations:**\n${recs}` : "",
        ``,
        evalLine,
        b.trace_id ? `*Trace ${b.trace_id.slice(0, 8)} · ${b.latency_ms ?? "?"}ms*` : "",
      ]
        .filter(Boolean)
        .join("\n");
    }
    case "graph":
      return `### Causal graph (rendered above)`;
    case "followups":
      return "";
    default:
      return "";
  }
}

function fmtPct(n: number): string {
  const sign = n >= 0 ? "+" : "−";
  return `${sign}${Math.abs(n).toFixed(2)}%`;
}

export function downloadMarkdown(filename: string, markdown: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyMarkdown(markdown: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(markdown);
    return true;
  } catch {
    return false;
  }
}
